config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'user_profile/show'
  devise_for :admins
  devise_for :users, controllers: { }

  root 'home#index'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'

  resource :user_profile, only: %i[show], controller: 'user_profile'

  resources :resorts do
    member do
      delete :delete_image
      get :new_resting_place
      post :create_resting_place
    end
    resources :resting_places, controller: 'resting_places' do
      resources :reviews, only: %i[create destroy], controller: 'reviews'
      resources :booking_enquiries, only: %i[new create], controller: 'booking_enquiries'
    end
  end

  resources :feedback_requests, only: %i[new create]

  # Admin routes
  namespace :admin do
    resources :resorts do
      member do
        delete :delete_image
      end
      resources :resting_places, controller: 'resting_places'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking_enquiry.rb
class BookingEnquiry < ApplicationRecord
  belongs_to :resting_place
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/, message: "Is not a valid email" }
  validates :phone_number, presence: true,
                           format: { with: /\A\d+\z/, message: 'The number must contain only digits' }
  validates :message, presence: true, length: { maximum: 500, message: 'The message is too long' }
end

app/models/feedback_request.rb
class FeedbackRequest < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/, message: "Is not a valid email" }
  validates :phone_number, presence: true,
                           format: { with: /\A\d+\z/, message: 'The number must contain only digits' }
  validates :message, presence: true, length: { maximum: 500, message: 'The message is too long' }
end

app/models/feedback_user_info.rb
class FeedbackUserInfo < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/, message: "Is not a valid email" }
  validates :phone_number, presence: true,
                           format: { with: /\A\d+\z/, message: 'The number must contain only digits' }
  validates :message, presence: true, length: { maximum: 500, message: 'The message is too long' }
end

app/models/resort.rb
class Resort < ApplicationRecord
  has_many :resting_places, dependent: :destroy
  has_many_attached :images
end

app/models/resting_place.rb
class RestingPlace < ApplicationRecord
  belongs_to :resort
  has_many :reviews
  has_many :booking_enquiries
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :resting_place

  validates :content, presence: true, length: { maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :reviews
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Этот контроллер будет использоваться для отображения главной страницы (лендинг-пейджа), которая содержит информацию
  # об отелях, отзывы, форму обратной связи и другие общие элементы.
  def index
    page_number = params[:page].presence || 1
    @resorts = Resort.order(created_at: :asc).page(page_number.to_i).per(2)
  end

  def new
    @resort = Resort.new
  end

  def create
    @resort = Resort.new(resort_params)
    if @resort.save
      redirect_to @resort
      flash[:success] = 'Resort was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def resort_params
    params.require(:resort).permit(:title, :description, :location, images: [])
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # Используется для управления информацией об отелях. Включает действия для отображения списка отелей, а также для
  # показа подробной информации о каждом отеле.
end

app/controllers/resorts_controller.rb
# frozen_string_literal: true

class ResortsController < ApplicationController
  before_action :set_resort, only: %i[show edit update destroy delete_image]

  def show
    page_number = params[:page].presence || 1
    @resting_places = @resort.resting_places.page(page_number.to_i).per(3).order(created_at: :desc)
  end

  def edit; end

  def update
    # Обновляем все атрибуты кроме изображений
    if @resort.update(resort_params.except(:images))
      # Если пришли новые изображения, добавляем их к существующим
      @resort.images.attach(params[:resort][:images]) if params[:resort][:images].present?
      redirect_to root_path
      flash[:success] = 'Resort was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @resort.destroy
    redirect_to root_path
    flash[:success] = 'Resort was successfully deleted.'
  end

  def delete_image
    image = @resort.images.find(params[:image_id])
    image.purge
    head :no_content
  end

  private

  def set_resort
    @resort = Resort.find(params[:id])
  end

  def resort_params
    params.require(:resort).permit(:title, :description, :location, images: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_resting_place
  before_action :find_review, only: [:destroy]

  def create
    @review = @resting_place.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to [@resting_place.resort, @resting_place]
      flash[:success] = 'Review was successfully created.'
    else
      redirect_to [@resting_place.resort, @resting_place]
      flash[:alert] = 'There was an error creating the review.'
    end
  end

  def destroy
    if @review.user == current_user
      @review.destroy
      flash[:success] = 'Review was successfully deleted.'
    else
      flash[:alert] = 'You can only delete your own reviews.'
    end
    redirect_to [@resting_place.resort, @resting_place]
  end

  private

  def find_resting_place
    @resting_place = RestingPlace.find(params[:resting_place_id])
  end

  def find_review
    @review = @resting_place.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(message_type)
    case message_type.to_sym
    when :primary
      'primary'
    when :success
      'success'
    when :danger
      'danger'
    when :warning
      'warning'
    when :info
      'info'
    when :light
      'light'
    when :dark
      'dark'
    else
      'secondary'
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/resting_places_helper.rb
module RestingPlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/home/index.html.erb
<div class='container'>
  <div class="row justify-content-center">
    <div class="col-12 text-center">
      <h1>Welcome to Our Resorts</h1>
    </div>
    <div class="col-12 d-flex justify-content-end align-items-center mb-3">
      <%= link_to 'Add New Resort', new_resort_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="row">
    <% @resorts.each do |resort| %>
      <div class="col-12 col-md-6 d-flex">
        <div class="card flex-grow-1" style="padding: 10px;">
          <div id="carouselExampleControls<%= resort.id %>" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% if resort.images.attached? %>
                <% resort.images.each_with_index do |image, index| %>
                  <div class="carousel-item <%= 'active' if index.zero? %>">
                    <%= image_tag image, class: 'd-block w-100 carousel-image', alt: 'Resort image' if image.blob.present? %>
                  </div>
                <% end %>
              <% else %>
                <div class="carousel-item active">
                  <%= image_tag "https://placehold.co/600x400/EEE/31343C?font=playfair-display&text=Resort", class: 'd-block w-100 carousel-image', alt: 'Placeholder image' %>
                </div>
              <% end %>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls<%= resort.id %>" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls<%= resort.id %>" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <div class="card-body text-center">
            <div class="beautiful-text">
              <%= resort.title %>
            </div>
            <h2><%= link_to 'Edit', edit_resort_path(resort), class: "btn btn-primary mt-2" %></h2>
            <h5>Hotel Location: <%= resort.location %></h5>
            <h5>Hotel Description: <%= resort.description %></h5>
            <div class="d-flex justify-content-center mt-3 d-md-none">
              <!-- Show/Hide button for mobile only -->
              <button class="btn btn-orange show-hide-rooms" type="button" data-bs-toggle="collapse" data-bs-target="#restingPlaces<%= resort.id %>" aria-expanded="false" aria-controls="restingPlaces<%= resort.id %>">
                Show rooms
              </button>
            </div>
          </div>
          <div id="restingPlaces<%= resort.id %>" class="collapse d-md-block">
            <% resort.resting_places.limit(3).each do |resting_place| %>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <h3>Room number: <%= resting_place.room_number %></h3>
                  <p><i>Room Description: <%= resting_place.room_description %></i></p>
                  <p><i>Bed capacity: <%= resting_place.bed_count %></i></p>
                  <b>Price per night: <%= resting_place.price_per_night %>$ <span class="badge bg-danger">SALE</span></b>
                </li>
              </ul>
            <% end %>
            <!-- View more button -->
            <div class="text-center mt-2">
              <a href="<%= resort_path(resort) %>" class="btn btn-primary view-more">View more</a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="col-12 col-md-3">
      <div class='pagination-filter'>
        <%= paginate @resorts, theme: 'bootstrap-5',
                   pagination_class: "pagination-sm flex-wrap justify-content-center",
                   nav_class: "d-inline-block" %>
      </div>
    </div>
  </div>
</div>