config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'user_profile/show'
  devise_for :admins
  devise_for :users, controllers: { }

  root 'home#index'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'

  resource :user_profile, only: %i[show], controller: 'user_profile'

  resources :resorts do
    member do
      delete :delete_image
      get :new_resting_place
      post :create_resting_place
    end
    resources :resting_places, controller: 'resting_places' do
      resources :reviews, only: %i[create destroy], controller: 'reviews'
      resources :booking_enquiries, only: %i[new create], controller: 'booking_enquiries'
    end
  end

  resources :feedback_requests, only: %i[new create]

  # Admin routes
  namespace :admin do
    resources :resorts do
      member do
        delete :delete_image
      end
      resources :resting_places, controller: 'resting_places'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking_enquiry.rb
class BookingEnquiry < ApplicationRecord
  belongs_to :resting_place
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/, message: "Is not a valid email" }
  validates :phone_number, presence: true,
                           format: { with: /\A\d+\z/, message: 'The number must contain only digits' }
  validates :message, presence: true, length: { maximum: 500, message: 'The message is too long' }
end

app/models/feedback_request.rb
class FeedbackRequest < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/, message: "Is not a valid email" }
  validates :phone_number, presence: true,
                           format: { with: /\A\d+\z/, message: 'The number must contain only digits' }
  validates :message, presence: true, length: { maximum: 500, message: 'The message is too long' }
end

app/models/feedback_user_info.rb
class FeedbackUserInfo < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/, message: "Is not a valid email" }
  validates :phone_number, presence: true,
                           format: { with: /\A\d+\z/, message: 'The number must contain only digits' }
  validates :message, presence: true, length: { maximum: 500, message: 'The message is too long' }
end

app/models/resort.rb
class Resort < ApplicationRecord
  has_many :resting_places, dependent: :destroy
  has_many_attached :images
end

app/models/resting_place.rb
class RestingPlace < ApplicationRecord
  belongs_to :resort
  has_many :reviews
  has_many :booking_enquiries
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :resting_place

  validates :content, presence: true, length: { maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :reviews
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Этот контроллер будет использоваться для отображения главной страницы (лендинг-пейджа), которая содержит информацию
  # об отелях, отзывы, форму обратной связи и другие общие элементы.
  def index
    page_number = params[:page].presence || 1
    @resorts = Resort.order(created_at: :asc).page(page_number.to_i).per(2)
  end

  def new
    @resort = Resort.new
  end

  def create
    @resort = Resort.new(resort_params)
    if @resort.save
      redirect_to @resort
      flash[:success] = 'Resort was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def resort_params
    params.require(:resort).permit(:title, :description, :location, images: [])
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # Используется для управления информацией об отелях. Включает действия для отображения списка отелей, а также для
  # показа подробной информации о каждом отеле.
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(message_type)
    case message_type.to_sym
    when :primary
      'primary'
    when :success
      'success'
    when :danger
      'danger'
    when :warning
      'warning'
    when :info
      'info'
    when :light
      'light'
    when :dark
      'dark'
    else
      'secondary'
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/resting_places_helper.rb
module RestingPlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/views/forms/_booking_form.html.erb
<div class="container mt-5 mb-4">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card shadow-sm">
        <div class="card-header bg-primary text-white text-center">
          <h2 data-bs-toggle="collapse" data-bs-target="#booking-enquiry-form" style="cursor: pointer;">Booking Enquiry(Tap to open/close form)🤏</h2>
        </div>
        <div id="booking-enquiry-form" class="collapse show">
          <div class="card-body">
            <%= form_with model: @booking_enquiry, url: resort_resting_place_booking_enquiries_path(@resort, @resting_place), method: :post do |form| %>
              <%= form.hidden_field :resting_place_id, value: @booking_enquiry.resting_place.id %>
              <div class="mb-3">
                <%= form.label :name, "Your Name", class: "col-form-label" %>
                <%= form.text_field :name, required: true, class: "form-control" %>
              </div>
              <div class="mb-3">
                <%= form.label :email, "Email", class: "col-form-label" %>
                <%= form.email_field :email, class: "form-control" %>
              </div>
              <div class="mb-3">
                <%= form.label :phone_number, "Phone Number", class: "col-form-label" %>
                <%= form.telephone_field :phone_number, class: "form-control" %>
              </div>
              <div class="mb-3">
                <%= form.label :check_in_date, "Check-In Date", class: "col-form-label" %>
                <%= form.date_field :check_in_date, required: true, class: "form-control", id: "check-in-date" %>
              </div>
              <div class="mb-3">
                <%= form.label :check_out_date, "Check-Out Date", class: "col-form-label" %>
                <%= form.date_field :check_out_date, required: true, class: "form-control", id: "check-out-date" %>
              </div>
              <div class="mb-3">
                <%= form.label :additional_information, "Additional information", class: "col-form-label" %>
                <%= form.text_area :additional_information, class: "form-control" %>
              </div>
              <div class="d-grid gap-2">
                <%= form.submit "Submit", class: "btn btn-primary", id: "submit-button" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/forms/_edit_resort.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card shadow-sm">
        <div class="card-header bg-primary text-white text-center">
          <h2>Update Resort</h2>
        </div>
        <div class="card-body">
          <%= form_with(model: @resort, local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :title, class: "form-label" %>
              <%= form.text_field :title, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, rows: 5, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :location, class: "form-label" %>
              <%= form.text_field :location, class: "form-control" %>
            </div>

            <div class="mb-3">
              <%= form.label :images, "Upload Images", class: "form-label" %>
              <%= form.file_field :images, multiple: true, class: "form-control" %>
            </div>

            <div class="row mb-3">
              <% @resort.images.each do |image| %>
                <div class="col-md-2 mb-3 position-relative">
                  <%= image_tag image, height: 100, class: "mb-3 img-thumbnail" %>
                  <button type="button" class="btn btn-danger btn-sm position-absolute top-0 end-0" data-image-id="<%= image.id %>">&times;</button>
                </div>
              <% end %>
            </div>

            <div class="d-grid">
              <%= form.submit "Update Resort", class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/forms/_feedback.html.erb
<%= form_with model: @feedback_request, url: feedback_requests_path, local: true do |form| %>
  <div>
    <%= form.label :name, class: "col-form-label" %>
    <%= form.text_field :name, placeholder: "Your Name", class: "form-control" %>
  </div>
  <div>
    <%= form.label :email, class: "col-form-label" %>
    <%= form.email_field :email, placeholder: "Your Email", class: "form-control" %>
  </div>
  <div>
    <%= form.label :phone_number, class: "col-form-label" %>
    <%= form.number_field :phone_number, placeholder: "Your Phone Number", class: "form-control" %>
  </div>
  <div>
    <%= form.label :message, class: "col-form-label" %>
    <%= form.text_area :message, placeholder: "Your Message", class: "form-control" %>
  </div>
  <div class="d-grid gap-2">
    <%= form.submit 'Send', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forms/_feedback_form.html.erb
<%= form_with model: @feedback_request, url: feedback_requests_path, local: true do |form| %>
  <div>
    <%= form.label :name, class: "col-form-label" %>
    <%= form.text_field :name, placeholder: "Your Name", class: "form-control" %>
  </div>
  <div>
    <%= form.label :email, class: "col-form-label" %>
    <%= form.email_field :email, placeholder: "Your Email", class: "form-control" %>
  </div>
  <div>
    <%= form.label :phone_number, class: "col-form-label" %>
    <%= form.number_field :phone_number, placeholder: "Your Phone Number", class: "form-control" %>
  </div>
  <div>
    <%= form.label :message, class: "col-form-label" %>
    <%= form.text_area :message, placeholder: "Your Message", class: "form-control" %>
  </div>
  <div class="d-grid gap-2">
    <%= form.submit 'Send', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forms/_reviews_form.html.erb
<div class="review-form-container">
  <% if user_signed_in? %>
    <h3 class="review-form-title">Leave a Review</h3>
    <%= form_with(model: [@resting_place.resort, @resting_place, @resting_place.reviews.build], local: true) do |form| %>
      <div class="form-group">
        <%= form.label :content, "Your Review", class: "form-label" %>
        <%= form.text_area :content, class: "form-control review-textarea", rows: 4 %>
      </div>
      <div class="form-group text-right">
        <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% else %>
    <p class="review-login-message">To leave a review, please <a href="<%= new_user_session_path %>">log in</a> or <a href="<%= new_user_registration_path %>">sign up</a>.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusinessProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <div class='container'> 
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <!-- Логотип -->
          <a class="navbar-brand" href="/">Hotels</a>
          <!-- Кнопка гамбургера -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Навигация -->
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <%= link_to 'About', about_path, class: "nav-link #{'active' if current_page?(about_path)}" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Contact', contact_path, class: "nav-link #{'active' if current_page?(contact_path)}" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Terms', terms_path, class: "nav-link #{'active' if current_page?(terms_path)}" %>
              </li>
            </ul>
            <!-- Секция для пользователя -->
            <% if user_signed_in? %>
              <div class="navbar-nav ms-auto"> <!-- Смещение аватара и email вправо -->
                <% if current_user.avatar.attached? %>
                  <!-- Для ПК -->
                  <li class="nav-item me-lg-3 d-lg-block d-none">
                    <%= link_to user_profile_path do %>
                      <%= image_tag current_user.avatar, class: "rounded-circle", style: "width: 40px; height: 40px; object-fit: cover;" %>
                    <% end %>
                  </li>
                <% else %>
                  <!-- Если аватар не загружен, используем плейсхолдер -->
                  <li class="nav-item me-lg-3 d-lg-block d-none">
                    <%= link_to user_profile_path do %>
                      <%= image_tag 'https://avatar.iran.liara.run/public/47', class: "rounded-circle", style: "width: 40px; height: 40px; object-fit: cover;" %>
                    <% end %>
                  </li>
                <% end %>
                <li class="nav-item me-lg-3">
                  <span class="nav-link"><%= current_user.email %></span>
                </li>
                <li class="nav-item">
                  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link btn btn-danger' %>
                </li>
              </div>
            <% else %>
              <ul class="navbar-nav ms-auto"> <!-- Смещение кнопки входа вправо -->
                <li class="nav-item">
                  <%= link_to 'Sign In', new_user_session_path, class: 'nav-link btn btn-primary' %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>" role="alert" >
        <%= message %>
    </div>
<% end %>