config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'user_profile/show'
  devise_for :admins
  devise_for :users, controllers: { }

  root 'home#index'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'

  resource :user_profile, only: %i[show], controller: 'user_profile'

  resources :resorts do
    member do
      delete :delete_image
      get :new_resting_place
      post :create_resting_place
    end
    resources :resting_places, controller: 'resting_places' do
      resources :reviews, only: %i[create destroy], controller: 'reviews'
      resources :booking_enquiries, only: %i[new create], controller: 'booking_enquiries'
    end
  end

  resources :feedback_requests, only: %i[new create]

  # Admin routes
  namespace :admin do
    resources :resorts do
      member do
        delete :delete_image
      end
      resources :resting_places, controller: 'resting_places'
    end
  end
end

app/models/resort.rb
class Resort < ApplicationRecord
  has_many :resting_places, dependent: :destroy
  has_many_attached :images
end

app/controllers/admin/resorts_controller.rb
# frozen_string_literal: true

class Admin::ResortsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_resort, only: %i[show edit update destroy]
  def index
    @resorts = Resort.all
  end

  def show; end

  def new
    @resort = Resort.new
  end

  def create
    @resort = Resort.new(resort_params)
    if @resort.save
      redirect_to admin_resort_path(@resort)
      flash[:success] = 'Resort was successfully created.'
    else
      render :new
    end

    def edit; end

    def update
      if @resort.update(resort_params.except(:images))
        @resort.images.attach(params[:resort][:images]) if params[:resort][:images].present?
        redirect_to admin_resorts_path
        flash[:success] = 'Resort was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @resort.destroy
      redirect_to root_path
      flash[:success] = 'Resort was successfully deleted.'
    end

    def delete_image
      image = @resort.images.find(params[:image_id])
      image.purge
      head :no_content
    end

    private

    def set_resort
      @resort = Resort.find(params[:id])
    end

    def resort_params
      params.require(:resort).permit(:title, :description, :location, images: [])
    end
  end
end

app/controllers/resorts_controller.rb
# frozen_string_literal: true

class ResortsController < ApplicationController
  before_action :set_resort, only: %i[show edit update destroy delete_image]

  def show
    page_number = params[:page].presence || 1
    @resting_places = @resort.resting_places.page(page_number.to_i).per(3).order(created_at: :desc)
  end

  def edit; end

  def update
    # Обновляем все атрибуты кроме изображений
    if @resort.update(resort_params.except(:images))
      # Если пришли новые изображения, добавляем их к существующим
      @resort.images.attach(params[:resort][:images]) if params[:resort][:images].present?
      redirect_to root_path
      flash[:success] = 'Resort was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @resort.destroy
    redirect_to root_path
    flash[:success] = 'Resort was successfully deleted.'
  end

  def delete_image
    image = @resort.images.find(params[:image_id])
    image.purge
    head :no_content
  end

  private

  def set_resort
    @resort = Resort.find(params[:id])
  end

  def resort_params
    params.require(:resort).permit(:title, :description, :location, images: [])
  end
end

app/views/resorts/edit.html.erb
<%= render 'forms/edit_resort' %>

app/views/resorts/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card shadow-sm">
        <div class="card-header bg-primary text-white text-center">
          <h2>New Resort</h2>
        </div>
        <div class="card-body">
          <%= form_with(model: @resort, url: resorts_path, method: :post, html: { multipart: true }) do |form| %>
            <div class="mb-3">
              <%= form.label :title, class: 'form-label' %>
              <%= form.text_field :title, class: 'form-control' %>
            </div>

            <div class="mb-3">
              <%= form.label :description, class: 'form-label' %>
              <%= form.text_area :description, rows: 5, class: 'form-control' %>
            </div>

            <div class="mb-3">
              <%= form.label :location, class: 'form-label' %>
              <%= form.text_field :location, class: 'form-control' %>
            </div>

            <div class="mb-3">
              <%= form.label :images, class: 'form-label' %>
              <%= form.file_field :images, multiple: true, class: 'form-control' %>
            </div>

            <div class="d-grid">
              <%= form.submit 'Create Resort', class: 'btn btn-primary btn-block' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/resorts/show.html.erb
<div class="container mt-5 mb-4">
  <div class="text-center mb-4">
    <h2><%= @resort.title %></h2>
    <p class="lead">Hotel Location: <%= @resort.location %></p>
    <p>Hotel Description: <%= @resort.description %></p>
    <%= link_to 'Add New Resting Place', new_resort_resting_place_path(@resort), class: 'btn btn-primary' %>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div id="carouselExampleControls<%= @resort.id %>" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner mb-4">
            <% if @resort.images.attached? %>
              <% @resort.images.each_with_index do |image, index| %>
                <div class="carousel-item <%= 'active' if index.zero? %>">
                  <%= image_tag image, class: 'd-block w-100 carousel-image', alt: 'Resort image' if image.blob.present? %>
                </div>
              <% end %>
            <% else %>
              <div class="carousel-item active">
                <%= image_tag "https://placehold.co/600x400/EEE/31343C?font=playfair-display&text=Resort", class: 'd-block w-100 carousel-image', alt: 'Placeholder image' %>
              </div>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls<%= @resort.id %>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls<%= @resort.id %>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center">
    <b><p class="display-6">Resting Places</p></b>
    <p class="fs-1 mb-5">☟</p>
  </div>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @resting_places.each do |resting_place| %>
      <div class="col mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h3 class="card-title">Room number: <%= link_to resting_place.room_number, resort_resting_place_path(@resort, resting_place) %></h3>
            <p class="card-text"><i>Room Description: <%= resting_place.room_description %></i></p>
            <p class="card-text"><i>Bed capacity: <%= resting_place.bed_count %></i></p>
            <p class="card-text">Price per night: <%= resting_place.price_per_night %>$</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="col-12 col-md-3">
      <div class='pagination-filter'>
        <%= paginate @resting_places, theme: 'bootstrap-5',
                   pagination_class: "pagination-sm flex-wrap justify-content-center",
                   nav_class: "d-inline-block" %>
      </div>
    </div>
  </div>
</div>